### ISSUE TITLE
Wrong "Latest version of qunit.

### ISSUE THREAD

**Issue by najela** [jquery/qunitjs.com#97] opened 2015-04-17 10:32 UTC

**Comment by arthurvr** [comment] 2015-04-17 10:37
Duplicate of https://github.com/jquery/qunitjs.com/issues/98?

**Closed by arthurvr** 2015-04-17 10:37 UTC

**Comment by najela** [comment] 2015-04-17 10:40
My bad don't know why my browser submitted double though

**Comment by arthurvr** [comment] 2015-04-17 10:43
@najela No problem! Thanks for your hard work lately!
